server:
  port: 8083

spring:
  application:
    name: payment-api
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/paymentdb}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    #    bootstrap-servers: kafka:29092
    topic: order-event
springdoc:
  api-docs:
    enabled: true

